title: "Il mio blog"
description: "Analisi su titoli, studi avanzati e portafoglio live"
url: "https://vanhell89.github.io"
baseurl: ""

author:
  name: "VanHell89"
  bio: "Analista tecnico e consulente finanziario"
  location: "Italia"

# Navigazione (menu in alto)
nav:
  - title: "Chi sono"
    url: /chi-sono/
  - title: "Analisi su titoli"
    url: /analisi/
  - title: "Studi avanzati"
    url: /studi/
  - title: "Portafoglio live"
    url: /portafoglio/

theme: minimal-mistakes-jekyll
